spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true